---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-external-ingress
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-metallb
    - name: cluster-apps-metallb-config
    - name: cluster-apps-ingress-nginx
  path: ./kubernetes/apps/networking/external-services/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 3m
