apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: network
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:HF67Le2LIaazpF867eaOrb8=,iv:jitpQLDoKVueNoOJ7qtc8HZRVn6t+jkUXMQ7ZLC0Jm4=,tag:Fr3mv/lOOa0FVb8hhMzW+g==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:6Au+z5jS2R3MXmJcqAuxaQEaOwYFiSzG/wJ6/ALWlJvzYgs+nQ==,iv:CRktNAcyidxcLCENsKeMYD8y+4l1t/UE+yfQ8RkwQW0=,tag:5TSjkYyZEW7oSQu+3Ng28w==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:XnSwiFcdp6DYd3+kGyWY6w==,iv:kNpUjLijUzwFFT4Y3xAwVYFEKftLyycaJFa68oMLDp8=,tag:S3Ir8eRqKwHLziC0vQwX6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNlhQTkI2SDk1OURPMkFZ
            b0hucis3QW1UQU1MN29IT3VLZEJWNkhPamhJCnFPazFWOHNzZXBjMkNBQnAvYzIv
            dE9xTHJXNDc4REsxa1BYT080OHZoTXMKLS0tIDRhZEFVVWxZNFc4Yi9qUW1yRVVN
            S1RZK2VVeVlvQUJHamJ2d01FZ25nS3MK9pezkJ3vIA2gqwvWj83RBBondZSSHr/j
            3pYs5XwLt2BL3QmfF7pd78LbcEZ77dbt1h0mx6mvQRyzDQAzdaH4pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T17:41:10Z"
    mac: ENC[AES256_GCM,data:vygr2YqsSzjiKklnOH9mSb8Db1tPoQD/RBsAwqyScV5CzdxOV3WUaptmdmm2z1S0wnJhhDRTsk6Y/h2pnU/cKtSoI66WelRA96xR56rYBBrCmvbEcG7dBvMD6ra8RfTB76QeQQ04lvREh8kZpd3+A5paQHIIwcC8OuOjGdIj2Cc=,iv:aSyqUAHfb9SEbvrI47XFluVtiikY+nN2qfEfpnj9B58=,tag:N/9VOtkzt5GPBhOUdE1XfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
