kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: database
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:hdAKwiHi+QNOJQ==,iv:p5V77HY9ZPu9pvXQX2Hm3dZpkMJTflKEGYV6QvDE5qM=,tag:bXuLFbw3XMQuivNRVGp10g==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:UXV18AnTJb7BOw==,iv:QbwiLQtXKxSOjpeqRjxxlhdTC0WA/QLu4vcEKt5GzU4=,tag:EciqIBkh0VU6VpQKQn7NXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Y0VnUlM1Ui8vK1pLRmJn
            QnlLeHdUWWJrQkU1cDZ4UXhTV01LNEJxMUFzCnRkZWdqelpjWXROSXB5VHRRQXI0
            eHZzOEhGcGJGWWYzRGdOSnFYOFBqdFUKLS0tIGZvajJTYkdIZUJ0bm5vZHhWanpj
            RGxFSStXVncramhySWdDNzl5RW1FcXcKWyr8apWL7CHTKDkbgzmi/VMK//7s0Qq/
            KFcc8Cn0cpLzSlb8Qd+EwHYNWXckgYs4k48764tidFeGqUeLkJptvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-16T15:19:23Z"
    mac: ENC[AES256_GCM,data:00/QZHFIYhukfJcTDKCs5qRgc/g7GNAjipUwUBL+z8vKPzkG6OSS+nDfm2VnKNZHX3xrd0IGsf1DDFiThb/TyJggmEURsaLFT2aiknx+EtclFt2Klk2fPuZ36YujJPX/HDijtP8ykAXnqSGMzwA8iMHxge11TOdP2CWyu6lzPVY=,iv:j55ergj6Ag1uOmkd4+189y9makDR3eNDo5FC1mFVObo=,tag:V7kaCoP0vVhrV0WkMONBnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
