---
apiVersion: v1
kind: Service
metadata:
  name: &app postgres-lb
  namespace: database
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app

spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: "${SVC_POSTGRESDB_ADDR}"
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres-v1
    role: primary