---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cloudflare-ddns
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-dns
  path: ./kubernetes/apps/networking/cloudflare-ddns/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
