kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: recyclarr-restic-secret
    namespace: media
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:A0Vo/Kv9f05loA6VgatfKYGgKlU38x+vj+gVG5Y1eu7F+wYD7kVNrHxDP8uv,iv:4bS9XiFrEeCSR1KAmNVan4vqFGhccqdch53P4V8KQjg=,tag:KDvkTwuvWfvQLWuy/642Aw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:PMqAVm9vvOSL55o=,iv:4mzCOOCzM4lhSXCf6Cb1vcjQt4FGb11xMOksZ0ef1CU=,tag:E1mgrQgbbTB8OflnQ19J7A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:8axRUpjx,iv:4w0TuSQ/cnAjr9etOQzQimeaktqdFG4wfXX62WNx6hs=,tag:jEUIAt0yFlqH+sIohe9ZlA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:arOBIF2jG76fNx5DfNo=,iv:K4ixvckm+4hQHZocCRCwY3Ufc+IKTY1IFBymfIvIL+w=,tag:tQnhekXqxhMu85VGzfC2zQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia2NIQXpYYUUvQmd1eW44
            Z0tQeGZxUjFPa0ZzQlB5MjM0TVlONGVxZ2dJCklJNUxtQjhPakliV0hJYXJ2WVFa
            TkdaK0lwdlRiUm9HSU9ZUlE0MXNIWjgKLS0tIDhJQXBicUQzSTdpN2FCUHVZVllk
            THp2bDdOdGg4S2ZscUtScHZLdmgyRDgKt1u3LByLvqiFtfb24QMQhZo7OQLdV1yS
            YK0Vg4nS79WWqji1TjZL5I1j6LKvnEsNoGOlOhE4W5TkDxfac1rb4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-09T01:57:28Z"
    mac: ENC[AES256_GCM,data:i5ay6LEhZaDpcDoK9YXYOljkTBvbU1vXObFr3Ayad7neh3oj07LL1sfp2pQC1+FYujSnz+YqCI7V1k5yees9aAR2uuOxtWzDzt4DP4oM7pPXUl5v90Xhp3cLqk3yjP8FOylTzdSrFFiOHgejSwL+mrQfCuDDi7YwyEHYn3Q8GQ0=,iv:c8OKp736A71CPtLmBJDCcu1/s/eAkY1iRTEEuMK+v1w=,tag:nr636Zfweqo300JFGoHN/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
