---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zalando-postgres-pod-configmap
  namespace: databases
data:
  ALLOW_NOSSL: "true"

  # Configure S3 backups
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  BACKUP_SCHEDULE: '0 5 * * *'
#  WAL_BUCKET_SCOPE_PREFIX: ""
#  WAL_BUCKET_SCOPE_SUFFIX: ""
#  WALG_DISABLE_S3_SSE: "true"
  BACKUP_NUM_TO_RETAIN: "14"
  CLONE_USE_WALG_RESTORE: "true"
  AWS_S3_FORCE_PATH_STYLE: "true"
  AWS_ENDPOINT: "https://s3.us-west-002.backblazeb2.com"
  AWS_REGION: us-west-002
  #WAL_S3_BUCKET: backup-prod-postgres
  SCOPE: db-postgres
  WALG_S3_PREFIX: s3://backup-prod-postgres/db-postgres
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}