kind: ENC[AES256_GCM,data:a/VsuEVm,iv:Sg6kEVN7tyU1NtNrQjmDRO4PvvjVImZAmWZlQtemFi0=,tag:SKLP8VVBsuR+yC9grEFqxA==,type:str]
ansible_user: ENC[AES256_GCM,data:c1Yk0vOm7A==,iv:HNOf4rlRAlte7r8ogwJIzSLSF8dJQakpiWX4rU6Uglc=,tag:eSUMCy+bZVXJUhy1pV1ddQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Pn6NVdrEb/fehCg=,iv:sDYdNykZcIRR6760LBA6CoA9DQ9TtIxdDZTgsjGvMyw=,tag:Tt3mVgGvCAsTOr8fei0/pA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFN29BclVQSFIwWUZ0ZTVx
            ZDRuY3k1M0xKTFk0S25PNnhITnZ3blZMRTNZCldwUXdUL0pnNDdxSTZsSVdSSEN4
            SHRtNk8rMFFxMGgweVhCV2loN2VzMVkKLS0tIGhuekNQaXo1NUU3Z05qb2YzaHI1
            ajVmSG0yNjVWS2V0SEhTUTBCMFUvQ1EKZFhFhr3XC3L31UtdbEBs2FvneeEv6lne
            uXEoikjyMsUUUAnkZaH13HgP8PePbAIk8/0kJgYV3CVp1bK0PfYPHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-04T13:51:11Z"
    mac: ENC[AES256_GCM,data:yaiA+c2drcrPIgYWLPF3EzyBcZ7sW7bi9eFbfSX38W02yZwjpfRwVW2qYcMxmmMsBRvObNRAyKslzKZX7vUQp/VUfOqe0Y0/G9zF7kyCj+ePuAUm4sd4sg6am5JMk0ONKpunIJWRVn0aolx+lhnSXzJiMpN9COpRitUkCHE03gk=,iv:HBDuA+4OzrA0maiQvb2uQHo1EivQbd9BAk4c3FIazh4=,tag:ISJI6MM5nsUVa14BA7Wuqg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
