---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-config-v1
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: ceph-block