---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-gatus-ep
  namespace: monitoring
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: grafana
        group: external
        url: https://grafana.${SECRET_DOMAIN}/api/health
        interval: 1m
        client:
          dns-resolver: tcp://45.90.28.101:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
