kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: wizarr-restic-secret
    namespace: media
stringData:
    B2_ACCOUNT_ID: ENC[AES256_GCM,data:H3E67/zhI24iIxXunmRUCisbnq2mQk+kbw==,iv:ZGtTslMjfSQjC/ty1t/LzkMx+Ik5shmk3AX5E5SnjFs=,tag:lJRrxH0OxoSH4e6gEku74A==,type:str]
    B2_ACCOUNT_KEY: ENC[AES256_GCM,data:/bGNMIrTAFrZ2nSSc03HgczfZmGkoqOWtLfIvUxGHA==,iv:EB1kLHqXzMJP+fKo2I/NJ8wAwxs9oBlEmnYpfKs7KyM=,tag:vIR7fpl6Oynq5qZtQbeemw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:KN6QlwbgSLpSwOH8,iv:f70mwshEG69lV+nuu0Tg/UNoFkq2110jMAiiMav1F+0=,tag:mzgRE10BJ5OQoQGVOdQ9EA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:PMqAVm9vvOSL55o=,iv:4mzCOOCzM4lhSXCf6Cb1vcjQt4FGb11xMOksZ0ef1CU=,tag:E1mgrQgbbTB8OflnQ19J7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia2NIQXpYYUUvQmd1eW44
            Z0tQeGZxUjFPa0ZzQlB5MjM0TVlONGVxZ2dJCklJNUxtQjhPakliV0hJYXJ2WVFa
            TkdaK0lwdlRiUm9HSU9ZUlE0MXNIWjgKLS0tIDhJQXBicUQzSTdpN2FCUHVZVllk
            THp2bDdOdGg4S2ZscUtScHZLdmgyRDgKt1u3LByLvqiFtfb24QMQhZo7OQLdV1yS
            YK0Vg4nS79WWqji1TjZL5I1j6LKvnEsNoGOlOhE4W5TkDxfac1rb4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-11T00:25:24Z"
    mac: ENC[AES256_GCM,data:4QSmp2NH4vEmt5w1F21QVzPNeSIZrsPEOLXTuAf5qoFdlP+C7XaVlJVkdl+tamT7yg0Ernq1gi39c5ZpkID1SACT9O6SqYfUKO0oXPlfyKvTdpEL6K7oGLtjTRTmyiRERpdj8cy9fcKfrXKxfaiElVlAgsm85IsZkyD38tg2Ujk=,iv:W/ZbZ4fJaTwlAW/lVFKAYv50ImE2Hg0SqtHSnEZ0PuE=,tag:xpwCAhng/K9CwRi5motorA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
