apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-zfs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 30Ti
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tank/minio"
