---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-zfs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 30Ti
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tank/minio"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-zfs
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Ti
  storageClassName: manual
