---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapshot-validation-webhook
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: snapshot-validation-webhook
      version: 1.7.2
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
      interval: 30m
  install:
    crds: Skip
  upgrade:
    crds: Skip
  dependsOn:
    - name: snapshot-controller