apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
    namespace: media
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:NEK275OP4pWySzVYZIHeDdYMvsNFDznhra9UzyUXUgw=,iv:tzri8tcySriZjoifo7mMH4kG13Cm6uXlfQPSG7RczTA=,tag:CqWctPOj2Udt6ZilGlmEHQ==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:u/nFdZry44sFNHxrHWIbL++RKndgrUukfCzzvBxFDFY=,iv:35eSpZalT9AMTq0KbTU+vAze2jNnX/xpJldwILUAnUk=,tag:CDd+s0Mvx+xOD+zvqNrivw==,type:str]
    TEST: ENC[AES256_GCM,data:v43uS38/xg==,iv:p2ikmCoo7bJvOqlVCULA3lgao2f6ewBIZ9h/PeBoIec=,tag:xDIWorv8lyDlW1CBYv7f3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TlRUam1SU2paek82ZW9n
            WnY1TUZsQ2pFdEZ5ZzNZelg3NUNWMUFnaVdZCktHTkxXc292dFViYzkxeHNBVVpy
            cEZrMFBDNldnMXF4dWFuMi9jbHIwNFUKLS0tIFE2YWczTERrOWE3a3JwT1hhaFBn
            TGJvb3V2Yi9Nd0JXOVVhVnR6RkI2ZGMK9HOhngtSRbuxieQV/i0c2esJ2l9DBa3z
            QkT6daFKJyMRpnqTz0OTSo/NFWIs6FEO1IlbcvI8AxosZNMzGp1E8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-16T20:50:20Z"
    mac: ENC[AES256_GCM,data:clknRIXFIZ8Rsv832oY7D0dWxe4Mp5Mnk0UoXzifZDa+Hcv7ahiX9Zdhjr1i474ciZx3iy+QsDqmx4XjU9bYnL82eqDcnxRx1EwzcgOigQu8T6BhweyCq/0EcWEvN8PWdYItFFoPB5swGnBy875OwXvHbpzWbsTGGUlwTGfcnSM=,iv:MjLubZDDTk2hO51UpTNtkfDmr4yjy0GuYYhYsAw8AGA=,tag:xw7OpZQ1wFAjveHFTa0wNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
