kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: sonarr-restic-secret
    namespace: media
stringData:
    B2_ACCOUNT_ID: ENC[AES256_GCM,data:iNtrRalVhbRRKxBoIwTfA5SIRX0qUqV7Xg==,iv:DD/GdcfLQY8xMtbKDuRQdxMOB5E/ozRTBsq+X+CES3Q=,tag:wwjq/YBGI2OX2jrODqpXkA==,type:str]
    B2_ACCOUNT_KEY: ENC[AES256_GCM,data:Xe6TayqNFUzhHv3NLbQIxpErO4n3OTamzJeuaQQYBQ==,iv:/4SJMvR/B4jCfODq8jMJd1kIj0vcSRDvYr9NueiFQMA=,tag:qF8JFVEocaQbQnr+Cy+5zg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:yP9gqmIEjBgaBgPg,iv:xhi4J+XMTmZXbCqt35GU0+PfnWar7WPzoWIVJZQXUSU=,tag:f418C7uc5eciwjVVgtm/fw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:PMqAVm9vvOSL55o=,iv:4mzCOOCzM4lhSXCf6Cb1vcjQt4FGb11xMOksZ0ef1CU=,tag:E1mgrQgbbTB8OflnQ19J7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia2NIQXpYYUUvQmd1eW44
            Z0tQeGZxUjFPa0ZzQlB5MjM0TVlONGVxZ2dJCklJNUxtQjhPakliV0hJYXJ2WVFa
            TkdaK0lwdlRiUm9HSU9ZUlE0MXNIWjgKLS0tIDhJQXBicUQzSTdpN2FCUHVZVllk
            THp2bDdOdGg4S2ZscUtScHZLdmgyRDgKt1u3LByLvqiFtfb24QMQhZo7OQLdV1yS
            YK0Vg4nS79WWqji1TjZL5I1j6LKvnEsNoGOlOhE4W5TkDxfac1rb4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-11T00:25:06Z"
    mac: ENC[AES256_GCM,data:MZLxGm9hVTTxaiuXi0BWcQgsqj4RToXImPFPtaVA7dZyFDoVemuFcmT3FNbL76xQT/fUwYWgR8botH671OzabaA3Sqa4BWQNnlL6bMvRbzolaCsRBZDI4xHqaedHVBzcl00jQxCPm8PAg/xhmNSO5wfhS/40zGmLomtjnWjVIeE=,iv:Dwc4qh2y9DS3olwNLqYk6UEVUlpz74IfeKoU8HbF8u8=,tag:7VGk+Prnm+ehU+vHflNDRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
