---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config-v1
  namespace: media
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
