kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: calibre-restic-secret
    namespace: media
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:h7nhnZK6LXOv0W8Fy06KSMatt1v/4i2mLSZgH23XnqWEgKnz4JKIDPRg+92V4XE7FnLr/cYKSJdPLglsEA==,iv:oTAf/g7z0tQE/D9+XEFIQ/+JF9Pk9d0C+g4TTVYZ3Ag=,tag:U3/9H7LlCG9e0l32IdAeFg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:PMqAVm9vvOSL55o=,iv:4mzCOOCzM4lhSXCf6Cb1vcjQt4FGb11xMOksZ0ef1CU=,tag:E1mgrQgbbTB8OflnQ19J7A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/YhDBZibW8wn3c7SZ77xAojUxt2BXjylHg==,iv:9aQmwxFUgtCHSa35M/s09ekJzsMnn8k90tG+vHUa3Q4=,tag:R3FlzjgS224XVOpW4ruHLg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:UNRaf7YwNmajuNvFfytFT9L7l5VgbkVa6uCAp3lV8A==,iv:NtXOy2YwqfxSLJ1wOF83wya6Bb35ch1Uv6qRtzvALiE=,tag:3QhyF23QJq/gwOg+gAgTJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia2NIQXpYYUUvQmd1eW44
            Z0tQeGZxUjFPa0ZzQlB5MjM0TVlONGVxZ2dJCklJNUxtQjhPakliV0hJYXJ2WVFa
            TkdaK0lwdlRiUm9HSU9ZUlE0MXNIWjgKLS0tIDhJQXBicUQzSTdpN2FCUHVZVllk
            THp2bDdOdGg4S2ZscUtScHZLdmgyRDgKt1u3LByLvqiFtfb24QMQhZo7OQLdV1yS
            YK0Vg4nS79WWqji1TjZL5I1j6LKvnEsNoGOlOhE4W5TkDxfac1rb4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T23:20:12Z"
    mac: ENC[AES256_GCM,data:mP35IKKouhoJj3KD+r8YblBOsA0PwPfCPdyz+NhbVazsCCyYX+H6foIGMEPmW66ixLZru3TZB8rWM/H+91fvxY8yoIWxUfBwrqKJHZQvZwKEF0pxkEdLp7An2TFu/8//BOgC+bxiREMpSE89vp/lAz88oagYHQx+dmFxz2lGJmg=,iv:KhnxtfLr4M3PdvWtdSwBRpxAp5JKboQs4+bQ2gJo79k=,tag:pfF4+kXVv7k1RxopvrfzPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
