kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: calibre-restic-secret
    namespace: media
stringData:
    B2_ACCOUNT_ID: ENC[AES256_GCM,data:09DXu7wRAEfwMMANW+fjrV6tTtkf9CkM7g==,iv:yqHDKNv507lnKpj7Ny1+RDfEoWY6UhMk2YPuWwMy78Q=,tag:NnOQKGEXdtOFpzN+Xcr6Vw==,type:str]
    B2_ACCOUNT_KEY: ENC[AES256_GCM,data:XxJZSExWsL863MBKL5YKowVjobW/f0skImzFZJeytw==,iv:Mju3mLV3hJU8zqosqrNCfbZnGb1+r6LoM4HrKKzjats=,tag:so3qorRxzwbPqfjJLVkAFg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:u9kWxOTWYjg2uYnOuw==,iv:jJR0IFr49tCISUtNay/w7FlKlRvMxH0/X6/AF57RZtk=,tag:L45cDSx1nS/bNS3HhlVTEw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:cp94BOHrOADWBw0=,iv:lJyqT+Q6MdAK3Mdhtt+LhXId4MPWpDSE83l4X+APdh4=,tag:68FGyrzII5FLO4i67m8aWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia2NIQXpYYUUvQmd1eW44
            Z0tQeGZxUjFPa0ZzQlB5MjM0TVlONGVxZ2dJCklJNUxtQjhPakliV0hJYXJ2WVFa
            TkdaK0lwdlRiUm9HSU9ZUlE0MXNIWjgKLS0tIDhJQXBicUQzSTdpN2FCUHVZVllk
            THp2bDdOdGg4S2ZscUtScHZLdmgyRDgKt1u3LByLvqiFtfb24QMQhZo7OQLdV1yS
            YK0Vg4nS79WWqji1TjZL5I1j6LKvnEsNoGOlOhE4W5TkDxfac1rb4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-11T00:22:46Z"
    mac: ENC[AES256_GCM,data:fNTajGuosAPsYrOqbSL2rIhH47rP+/PJB6rw7hcn78PeKYW6+XbT/Mets7pRqnAYTYjsalD2WVdpdyzEAfX8DX/LAKAIchpGe9JAOpdbZPlj1QOd/3kR7fladaCO/bk1Inc6V+B1M856vDIru+f1GTqTOyFSs1dDRu2naSyE6ew=,iv:oNWB6DdQsu8HW8/GelEohD78MRhx2+NDmXhoFL+w7y4=,tag:JfdYCmqRyO3Ag3KJe/+hOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
