kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: calibre-restic-secret
    namespace: media
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:1z1ukqZOgizZF4o4MWpqpwHvmyMa0TuYuKWEumVlnHI5SZ0+pCkZ3zC7Ulv5Le8snK7ytoA=,iv:ZqUxk0F39LcXBrt+7cWBNORw5hkL0jWH0ToiGiuh3LE=,tag:/N7ZbaD/z8zqUQkJ7W/GKQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/YhDBZibW8wn3c7SZ77xAojUxt2BXjylHg==,iv:9aQmwxFUgtCHSa35M/s09ekJzsMnn8k90tG+vHUa3Q4=,tag:R3FlzjgS224XVOpW4ruHLg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:UNRaf7YwNmajuNvFfytFT9L7l5VgbkVa6uCAp3lV8A==,iv:NtXOy2YwqfxSLJ1wOF83wya6Bb35ch1Uv6qRtzvALiE=,tag:3QhyF23QJq/gwOg+gAgTJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia2NIQXpYYUUvQmd1eW44
            Z0tQeGZxUjFPa0ZzQlB5MjM0TVlONGVxZ2dJCklJNUxtQjhPakliV0hJYXJ2WVFa
            TkdaK0lwdlRiUm9HSU9ZUlE0MXNIWjgKLS0tIDhJQXBicUQzSTdpN2FCUHVZVllk
            THp2bDdOdGg4S2ZscUtScHZLdmgyRDgKt1u3LByLvqiFtfb24QMQhZo7OQLdV1yS
            YK0Vg4nS79WWqji1TjZL5I1j6LKvnEsNoGOlOhE4W5TkDxfac1rb4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T23:36:49Z"
    mac: ENC[AES256_GCM,data:NCSyXiDXtzIa9zzVZ4L+hIb8bPdOtNP4h1ErVZy6VuTxIzrL5BTs5f/+qziETeWDB8saNTG7A0FZBRUsuylCsm+8nAROO4/kxuTdGswslRMURIp5k52DAgrf3+X6dR+YBLlRiY7jzbUd8+eUm1IOKJwmGyoEoZ+vbIEy0bCBSYs=,iv:jjcoyD2j3ZzdHrEzP/OhAhAGJBjziVRqA8pemqCZtTA=,tag:gZ3ccVxCRJi1i0AvGcmwew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
