---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-postgres-backup
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/database/postgres-backup/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-zalando-postgres-cluster
