apiVersion: v1
kind: Secret
metadata:
    name: longhorn-secret
    namespace: longhorn-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:NmTZ/uSdFIMN0u/dZY5PXFXF5AqEx3VX2YOLcm2+fhk2Cwea,iv:fA8oK33NSBijmD74zEwSHZyzmRhovNfSObsjJtmN1LU=,tag:oRf6JTacU5Q1ed86HKRMHw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BzGf839Z/iffvcVNBa0xMJdNC6Ljb1QRZdx+qC+BwaewZAuD4hhHuYP3VNg=,iv:c0DJdBlghxRANTJ3eg+dy+g7NHhDztKH0oG9zmVoCqo=,tag:tjeh8sxHOKfVjHcHog2YZw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:ohYu0UFO08W7kQ8OFJxtiZJ7VnjR4q8pmcb3EQHCPYTf8PoaL0I=,iv:C4FW90aKN0/+P+bRXBD+swUgnjqclzGZJHxHRuPZoK8=,tag:sGk19Uye+IQPQ8bR6o/GOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZnJ1d05JWktxSEYrcENi
            WW56UE01dk9jRm9ZaUR3eVRTa2NKOGp4eW04ClhFQ0Z6ZzBqSEFKcDBvTmc3ZHlt
            ODB1aWNTSmpKT2hqK3JsWGp5UFpoamcKLS0tIEhGU0tmbyt3Z2tFSHgvTW5neTh3
            ZXBtenZuWkVQcEZGNVhJOGQ1TnQ5MkkK3/MZL4KGwBiSHpLmtW0J3HpqFEy7gLPE
            SwIhCUDEE/6CFWmMx3BosBD8zSoq1tZbrbl3zBXiV72h5ycw+/zDww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-11T23:11:33Z"
    mac: ENC[AES256_GCM,data:osqA3tDr3jGG46G9f+n7A1a2Z5uKlyTJSv5HneVsbhaEaonllrZtODpoO58vHAdlYXJGSiaealn5XqVddwawv0ik57/Rh5Ox+JsMSJUGEvmTMlQeEloRZ2p9jQtTno6wm4e2oI7a79LibF7NueC7kBvG+Y2keh6oXDhOih1wVkI=,iv:7m6EuskXbMDDztQXy0LnC6oJyIJmKkOmVWDknAayokU=,tag:xsNq5eBPKWLdjBO6vbmZvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
