apiVersion: v1
kind: Secret
metadata:
    name: longhorn-secret
    namespace: longhorn-system
stringData:
    AWS_ACCESS_KEY_ID: 002af3077ab7123000000000a
    AWS_SECRET_ACCESS_KEY: K002UYJxapslRsxEmBD0V86iTqHVI1w
    AWS_ENDPOINTS: s3://madk8slonghorn@s3.us-west-002.backblazeb2.com 
