apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:tErJka25hPbjqPw3l7HKVbIaDhaXvTCtSt2MaiDOzQvsRd3JIA==,iv:MrVhPidTWd9bR8EFmjbBTP155v9wWf9BAokj4fhyUlw=,tag:wg7iP3KfCF0qfK9fHL//Rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYemEwdVFTaTREV2c2cVhZ
            NFFzYmtJeVVNK2Y2eHVCTVF4RlF2RDFRaVFzCklVSldqbmVTMWpDajJYK095bWRa
            YS9nS1dON01hNVhKQmxnZ0dvWVRRMXMKLS0tIDhFaThEa2tFdmUxTUdacHB6c1dG
            YTVKTmUram5NMDJRcHY1aWtkWUpsbVkKnCKroBm4mIY0L/YB0q41/WhHzWvxbjIO
            vYQKMIERoZvdmw7i8nb4FqlgJMOG4OX5+8fSkepPE0R4JkVDMCkbAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-04T13:51:11Z"
    mac: ENC[AES256_GCM,data:c7AHeJ76y4zCEd9yBnOBtk3qxUD+htGA4XyDZr05eItvChzG4UJYjb1/ulnn57PgPvuYDyrR6l279tuXKAFYZU1R0Ab3DC/GoEzP1xknJY6gxW2JPRw7tMfmVFySlzV3vsy9acg9WRXWkdlLzqnLL41pY+ceMHxFZHAHBAzHTtU=,iv:+Rb/LqWaiGhJeaFZwJRjcpnfGJpUbCl47oy8ppxVT3s=,tag:93FXyYVTs3t0JA1sJpv4dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
