apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:lo1Qmlt/8L0ee4qGyBY4y88=,iv:g2+8emoBzCo6z6KN3/WM/3zH0f3PM0Y1SW1igwd2pOg=,tag:y/FaAmY9LkpwqbITTAHiJA==,type:str]
    api-key: ENC[AES256_GCM,data:pD3WbPEZ6Nq366AKm/NOIywe8coHHbdo3OIlbN44L1KBgVlqCQ==,iv:b0ZhA7h7J6v+LDktoyMAIroZAVfIjuY9hm2pgD38Dj4=,tag:ztT/taDo3Ed+Y/jwv+G9ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFY3VyY0NzQy9BNzZkaGlL
            SnFLcWFOMGRVL252VS9sbjRuZjU3WFJMMlVZClJkcGRKR2ovVzVvMFZGV2hIdGJy
            cGY4MFNGVVExTHordWpieWJYd25JZUUKLS0tIHQ0NEFPM2UvWGhtczlqbnUzOHEw
            UG51b3ZDYVhxUWdSenRzRnV4N00vS28KpV3A9AoQm3X0HdTQC7qSxgIH+9i9ScJ/
            zdcGxpMJnWpetR4ZmnCRK3SoHLC+qU2qlmF0wRcfVVfU1VeEc6BGdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-03T22:43:47Z"
    mac: ENC[AES256_GCM,data:W8jO+yZ7C92tdLrifBsFwchQFPIALSGZzwTmWNMOLgS6b4xYbTlfZv8YDvu03MGvAbwgmDSnUmUTb5Ut52XYqoZ5MaKgm+dAactQdd8DsPN9v8K/kD6nfzA32iGrnh5rN261PhXa80wW/H8ob5BwYLDPIvBTOp+DegFMHvmcar8=,iv:MvRD7twnnDMGmdbEVmLYeIyde80i7ouQMOTjWtTwqn8=,tag:yalk3aZq9BwtDNsPjeuMsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
