kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: readarr-restic-secret
    namespace: media
stringData:
    B2_ACCOUNT_ID: ENC[AES256_GCM,data:ka4AU28PM/IHuUkL+IH3PRQ1FzPfj1b5Xg==,iv:d1k5RMADxo80vijBim+fA3VSULxvKAHXgoOVl3LWbGI=,tag:7IbWMlRKaelOOOUa0ixQcA==,type:str]
    B2_ACCOUNT_KEY: ENC[AES256_GCM,data:LR/fIzkyaJBK7nqF3Uroo6lrMAZ1wuuOKPTO0SsoHg==,iv:s9lfqJJ5UrHJMbRHIac3YARSRdpYJgYnilAmJH89EZk=,tag:XDUqp9w6BgebVCswu+rZMA==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:863za/cShkobSOwX9g==,iv:Dhjd7gQhggThVPorV4Q/FV+rkUKu1DxkrqfRSPEYs+A=,tag:3BpoKZEcBBonHH33xwS/ww==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:PMqAVm9vvOSL55o=,iv:4mzCOOCzM4lhSXCf6Cb1vcjQt4FGb11xMOksZ0ef1CU=,tag:E1mgrQgbbTB8OflnQ19J7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia2NIQXpYYUUvQmd1eW44
            Z0tQeGZxUjFPa0ZzQlB5MjM0TVlONGVxZ2dJCklJNUxtQjhPakliV0hJYXJ2WVFa
            TkdaK0lwdlRiUm9HSU9ZUlE0MXNIWjgKLS0tIDhJQXBicUQzSTdpN2FCUHVZVllk
            THp2bDdOdGg4S2ZscUtScHZLdmgyRDgKt1u3LByLvqiFtfb24QMQhZo7OQLdV1yS
            YK0Vg4nS79WWqji1TjZL5I1j6LKvnEsNoGOlOhE4W5TkDxfac1rb4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-11T00:24:39Z"
    mac: ENC[AES256_GCM,data:UdmyGMDluBAZJP1T16GmJe1QQVvbv2Kn/1pWcxpV2Qy2219R3lHPUVKYfaJzMfI4k52VsMdm+xzNvTCtX+MbSPEHWuR2PSbw1EASIawzccXAFZVuAN8smc2bjKzUwm4HwAVoTvDi4UMyfmviaMimHw8uAdPhDi6oahftGDW2NNQ=,iv:bcSK6NdjvsNk6hGkj8HuUYAbn8JfxN7zZSSKdnb73Bg=,tag:LX2iGSv+hz7jPqNvdNWJzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
