kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: prowlarr-secret
    namespace: media
stringData:
    PROWLARR__API_KEY: ENC[AES256_GCM,data:MS1X6XohlrZFrqljbwkPl18dsW/89SFJiONDsBoIB50=,iv:beUJvqrpcx1f+9+UD+JD8tkp/IGk3Su6MCyIWzDuX+E=,tag:sFXWA1mLWZdMBVWZ+4lF8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOK2dua0pEU3U2Yzhnb0tO
            Yndnc1NDblZuSTZHSmhRR3RqVEhPb1Z1ZlEwCjlBM1c5aVpKeW96OVFsdkYvcEtk
            blpTeWVSWEo0NzI4OTBqWkFmY054TlUKLS0tIG0vK2U0MHRpejViRDRVU0FVK2FI
            ZGZtc2M3cTh5bXBEZnBYRmh2dC9sRWcKthub+wJpkcrikoDu9/YkWtM9zaShLzjB
            4v3Z/vOm479kkX3p7qBoXoWfgJW2g4ArK59CMNEbxQcxWQgbBpJQbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-07T01:13:40Z"
    mac: ENC[AES256_GCM,data:WXg5CLJ7bqgBS78PP3phAwNBsF/3HkS1zYorVjJ2voGfBaCbIWTZngCZSO9W2lfdrO7maIweFfRK5eTTEgxi7pm+IqrcubK4Jq66e7VN7GXwRqP8LyFeTdm6cDC36WLI0G3VcHWWk4WL5q9UJTt3AwQDBZ08n6aGkW0opR1MxfU=,iv:BmIXNHA5WZeG7rDKMXs0/3qc4bCvxeG5wXcvyBgbzfA=,tag:v4z1QrVykXCFQ6BCJ/tqgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
