kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: prowlarr-secret
    namespace: media
stringData:
    PROWLARR__API_KEY: ENC[AES256_GCM,data:MS1X6XohlrZFrqljbwkPl18dsW/89SFJiONDsBoIB50=,iv:beUJvqrpcx1f+9+UD+JD8tkp/IGk3Su6MCyIWzDuX+E=,tag:sFXWA1mLWZdMBVWZ+4lF8w==,type:str]
#    PROWLARR__POSTGRES_HOST: postgres.databases.svc.cluster.local
#    PROWLARR__POSTGRES_PORT: "5432"
#    PROWLARR__POSTGRES_USER: madbuda
#    PROWLARR__POSTGRES_PASSWORD: QueenBuda44
#    PROWLARR__POSTGRES_MAIN_DB: prowlarr_main
#    PROWLARR__POSTGRES_LOG_DB: prowlarr_log
#    # Postgres Init
#    INIT_POSTGRES_DBNAME: prowlarr_main prowlarr_log
#    INIT_POSTGRES_HOST: postgres.databases.svc.cluster.local
#    INIT_POSTGRES_USER: madbuda
#    INIT_POSTGRES_PASS: QueenBuda44
#    INIT_POSTGRES_SUPER_PASS: jixELN8R183twe0zqqy1IuYzHXZfcHLJiUvXWKIGgkvhFs7jMKByyD0RiY6jAQjd
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOK2dua0pEU3U2Yzhnb0tO
            Yndnc1NDblZuSTZHSmhRR3RqVEhPb1Z1ZlEwCjlBM1c5aVpKeW96OVFsdkYvcEtk
            blpTeWVSWEo0NzI4OTBqWkFmY054TlUKLS0tIG0vK2U0MHRpejViRDRVU0FVK2FI
            ZGZtc2M3cTh5bXBEZnBYRmh2dC9sRWcKthub+wJpkcrikoDu9/YkWtM9zaShLzjB
            4v3Z/vOm479kkX3p7qBoXoWfgJW2g4ArK59CMNEbxQcxWQgbBpJQbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-12T19:19:34Z"
    mac: ENC[AES256_GCM,data:9PX9F5aragdoEI/wcr/h/pnOe7iegVVOLf3mZBR0qCMo2uaqjC8MrbOLCFtI6c+dlQ4DBjAgxm9ZDd2o5l/0CUb0oN5w9NHKMK9kv2t6CbG7v49DOradPL9LAU1MXTzRAWBjFHvOkMiI5B5TkJ4iz92jzQv4e4oLLvHbTfZnNSc=,iv:Sp7NmYJajB8KOQWVKtRnHcvaLDn+9e74izWbazeX0Tk=,tag:Bfc2hmtxjSFGh3hPfJbQfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
