kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: prowlarr-restic-secret
    namespace: media
stringData:
    B2_ACCOUNT_ID: ENC[AES256_GCM,data:podhKR6wwFeakEFYPKcVTokSNqTc8eifSA==,iv:t4S/a4Nys3hJAkHwTBfbn92SNarJJjawyyF/r7CW5fI=,tag:UxIjJ3W9EHIDe5OCtc1CtQ==,type:str]
    B2_ACCOUNT_KEY: ENC[AES256_GCM,data:ES0xc2k0l7BryLQGWbatHB0H76n+gHhJ9pF14Gt+qA==,iv:J5ul7CZchFmDp2bsgBZk4NtzHZKGHeWgGCjwCu9n/10=,tag:K4/9HzkMsW813ocZO+jHZw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:sN6Eldk2MCbuBSLnXfc=,iv:Uezc9nsaCQGELyDsmFQJibu6++tdbOCxjzFTxBEbHmg=,tag:jG8IhRi8esAyoolnPCl/+A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:PMqAVm9vvOSL55o=,iv:4mzCOOCzM4lhSXCf6Cb1vcjQt4FGb11xMOksZ0ef1CU=,tag:E1mgrQgbbTB8OflnQ19J7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia2NIQXpYYUUvQmd1eW44
            Z0tQeGZxUjFPa0ZzQlB5MjM0TVlONGVxZ2dJCklJNUxtQjhPakliV0hJYXJ2WVFa
            TkdaK0lwdlRiUm9HSU9ZUlE0MXNIWjgKLS0tIDhJQXBicUQzSTdpN2FCUHVZVllk
            THp2bDdOdGg4S2ZscUtScHZLdmgyRDgKt1u3LByLvqiFtfb24QMQhZo7OQLdV1yS
            YK0Vg4nS79WWqji1TjZL5I1j6LKvnEsNoGOlOhE4W5TkDxfac1rb4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-11T00:24:21Z"
    mac: ENC[AES256_GCM,data:b9FODJKQ1b3cxGuEev95ZO5Pe/ovZVtlhHLgzAJI+8/z/Ae/Vup9ifzAqxi005KepGeNlogQlfF9IXYccecpU+9m7kqH2N/+DXXEhKvuRttqICMyaQrWfPug+4G5fvLpMhoc34MHXVRmfcunKSSXzDYu7SdiEmcr+IBglTKvuJU=,iv:CDujCmVlWi+DEjfGNmq5A5ChtvnrpRRXn6FFViA6YG4=,tag:iuO1EQdOycQurrJ6P5fZCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
