kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: prowlarr-restic-secret
    namespace: media
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:2QZ6CTEhmJVm2h3XFG8vYRnRilt9Zp21eUf0mygYWocFDKBiADuF98hjzTs=,iv:rwCCNxfHWt3SiatnWJMQ8SgatwwIj/WC+3h0+KsIhGQ=,tag:SaPFlc9tS4+i9J2QpOyS9Q==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:PMqAVm9vvOSL55o=,iv:4mzCOOCzM4lhSXCf6Cb1vcjQt4FGb11xMOksZ0ef1CU=,tag:E1mgrQgbbTB8OflnQ19J7A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:8axRUpjx,iv:4w0TuSQ/cnAjr9etOQzQimeaktqdFG4wfXX62WNx6hs=,tag:jEUIAt0yFlqH+sIohe9ZlA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:arOBIF2jG76fNx5DfNo=,iv:K4ixvckm+4hQHZocCRCwY3Ufc+IKTY1IFBymfIvIL+w=,tag:tQnhekXqxhMu85VGzfC2zQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia2NIQXpYYUUvQmd1eW44
            Z0tQeGZxUjFPa0ZzQlB5MjM0TVlONGVxZ2dJCklJNUxtQjhPakliV0hJYXJ2WVFa
            TkdaK0lwdlRiUm9HSU9ZUlE0MXNIWjgKLS0tIDhJQXBicUQzSTdpN2FCUHVZVllk
            THp2bDdOdGg4S2ZscUtScHZLdmgyRDgKt1u3LByLvqiFtfb24QMQhZo7OQLdV1yS
            YK0Vg4nS79WWqji1TjZL5I1j6LKvnEsNoGOlOhE4W5TkDxfac1rb4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-09T13:43:48Z"
    mac: ENC[AES256_GCM,data:dFh2e0IDu3C+ul9A9ScrjvLGJSM/az0Srx1eh8TQq3eWwoQ8YX2GxQAGAmR+Rv4HaJbgfrvkW2ktHAuKgMtEP1Ir0exJ7Ieol2rbQUb8rVkWnonheNf4PkddlCYraqsI8dc4DaIjfD7a0KXw5rc9Avi9WCyq+YJZMHB6nQUrsQM=,iv:NwuGQmSeDb6TZUfpWhRxvSo1x7yKe9iD1/NyrdtZjC4=,tag:7/yT5F095QgDFA2KaOrd5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
