---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: public.ecr.aws/docker/library/eclipse-mosquitto
      tag: 2.0.18

    initContainers:
      copy-config:
        image: public.ecr.aws/docker/library/eclipse-mosquitto:2.0.18@sha256:d84c9bd554489b5fa564df57d2d12c2e734185b2b2bfd8d62f9f91cb2cc0cdba
        command:
          - "/bin/sh"
          - -c
        args:
          - cp /data/mosquitto_secret/* /data/external_config/ && mosquitto_passwd -U /data/external_config/mosquitto_pwd
        volumeMounts:
          - name: mosquitto-secret
            mountPath: /data/mosquitto_secret
          - name: external-config
            mountPath: /data/external_config

    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${SVC_MQTT_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883

    persistence:
      mosquitto-config:
        enabled: true
        type: configMap
        name: mosquitto-configmap
        mountPath: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
      mosquitto-secret:
        enabled: true
        type: secret
        name: mosquitto-secret
        mountPath: "-"
      external-config:
        enabled: true
        type: emptyDir
        mountPath: /mosquitto/external_config
      data:
        enabled: true
        mountPath: /data
        existingClaim: mosquitto-data-longhorn

    resources:
      requests:
        cpu: 5m
        memory: 10M
      limits:
        memory: 10M
