---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
#  - ./config-pvc.yaml
  - ./mqtt-secrets.sops.yaml
  - ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: mosquitto
  app.kubernetes.io/instance: mosquitto
configMapGenerator:
  - name: mosquitto-configmap
    files:
      - config/mosquitto.conf
generatorOptions:
  disableNameSuffixHash: true