---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-zalando-postgres
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/database/zalando-postgres/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-zalando-postgres-cluster
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes//apps/database/zalando-postgres/cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-zalando-postgres
