kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: radarr-secret
    namespace: media
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:bdKOPrzrQXKMa4w8OObJo6Z9oRXJGSNyOVWLYYd+fFw=,iv:ImVMF6cabDElrkDMcanvRL1BPUaTbmKKyn/kNXXGg4o=,tag:U1rXjNsOlOiTwXo5maJZ6g==,type:str]
    #ENC[AES256_GCM,data:zgJu+0BZyL2YYiOTQUzqX/0123lXr4I6mFQ2oP2qJhCuqg6KpaFKN0nnvHuL3/yUXOcHXENH9JLHHs6BW9Oj,iv:RvLfnBqJQi2K9UyNrmMxp4X6MO1xR+GPC2yOz9LpTMs=,tag:LsZJaUnwfhICDt04fh+JGQ==,type:comment]
    #ENC[AES256_GCM,data:hiBkrchxsKrWN1B38vuhZ9HKQ8UZ+n+XBhg+fwi0qNB2,iv:N9mUECLmzy8hUTtSD1Eg4gzR82pLqUOuId9n6PhD1yQ=,tag:7b9l6EElX3fofh95OkjGZg==,type:comment]
    #ENC[AES256_GCM,data:omSrLh03hTIpYeFtLv1WS+EcMjgkfp999WmJ4qgQjAUPSA==,iv:+xE98uluGgZxsqZSoQtFJ3QTMRINe9kQqMLB0yb5xxg=,tag:XqIvMLwdhj5AAydcJCXfaA==,type:comment]
    #ENC[AES256_GCM,data:xC4K3NbXXdbaFKX5mp9TS8iYcAT883xGCXyXBpvmnEVGZYQ+Cdb+cpmR,iv:WXMfIT0BipXzvL2Q6RKU+B2sBBkwBvqsI60AB2crIG0=,tag:0g4+v/Po3usjhJ8ZJ9tk3Q==,type:comment]
    #ENC[AES256_GCM,data:9c4+hykk7195d8AlECSexYkB87NOv8mWd9bxLrmX/rXDF6WGcQ4vzhw=,iv:tdRnYLg+FEaZz39PoZ9rgnsYhJ56wRxIoOri6O0awKQ=,tag:Fezs1Y4nQkYVBUganG9rBw==,type:comment]
    #ENC[AES256_GCM,data:IBP5vygH0WOvj51FXQjzQtgwkJK1J9NwvpJ4UyKssnBWz8qj5D9g,iv:8L+DKvnHvsTvr02V+LRuJ2nE6Kx1yFRzIYxUfA8/3rg=,tag:dLWdh/IcEdvltXoBUXMaLg==,type:comment]
    #ENC[AES256_GCM,data:W1BJ+5d9h4afeGxuYoA=,iv:BUn1siXZJ6CFsfHh6yJj8z2kG2FLoiR9u2JF/auk23Y=,tag:a0tt0MfFaCCYslT+3+OHYA==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:2Mc2TBLW30aKrvXeNoQLM1WFyc0vOg==,iv:U1ZZolrokJuecs7wgYyYgPKMTGiYs8DOSh4EX5FKnEg=,tag:bi3qkP+fOOFT7xdr9Z2kHg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Qpi78OxCvA/MuhINSy//eaTihSqZsYyMTmYlQ07mKFBVqeJB,iv:MmNCVNr+MwRTdZcveiXF0FpIRgcV4PY3r+3zj2NGEXw=,tag:4Y2plrCmcXZDh7DO23ZKQg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:5T2kVht3DQ==,iv:BQTFRXQgiE8sBBhAidQqSPQBUHDBARRKZoycDDnM47o=,tag:3IpU6X/qNxyoDQfCmBWwrg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:5Fjt9JaKwzqS9Nw=,iv:X+iYaOtLnXwsp8qM076G/dUxtYhemFr8U84/id/+LiI=,tag:YZRg/rdYXKgxMTkK21rK6w==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:H5hMHROiWd8U9SeCNzts+lf0h9Bx+KXW5tG4zrKJJxG/qeQUpRlXbp0iYhLFCy3TT92Vofu1Y5EU1lh234X/XA==,iv:uIbg/tB86PHBScafDlnD+j6ukDZrDwVO/ofE7ODiqGg=,tag:Xf2mWoa7bBNQ+Q/8glMfRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSXNKWFAwUHR2YzJYSWo2
            bVY2djlybDl6UElNbHBoV0xRc2JPOXkzTmlnCmljdDJ0VjhmQjFISmlyK3pZT0k1
            R2JjTWF1U21PK096NXpzYk1QZmVGdTgKLS0tIHJXUGlvM2FEN0RiUWRLWTd2ejY4
            QjVUNkNBWEE1MW90RTZ2a0FmRGROaGMKt+IrQn0OWd6Mp63vISOAZLxLdjLiYM7L
            d5/KO+1vnREdMuvzg7tKq8o+3rUOp9tG57YVYAMkCLv2a0I/mixVDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T21:28:48Z"
    mac: ENC[AES256_GCM,data:9U+H8klIOoht6PXTQdILbmZjhuJDNq2VpI1a/8PbP5Rm4bGC8gPnxQI7PB/WY/9pL/hvk2mAo/USWst2f8+PuhTT68a+4tfTRn3365Emwe5wYRmWKLIXFjBdbpavrCRxB5f89KSVaNA/mAo7U+qil0tl/MMIqHN3z1xE7R+aMKo=,iv:YoHvN3YTK25a6rMwnMNMelsUF5NqTnZUlTbUSdol4To=,tag:dmnvbNS/OhMnMb2QzIoYBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
