kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: radarr-secret
    namespace: media
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:bdKOPrzrQXKMa4w8OObJo6Z9oRXJGSNyOVWLYYd+fFw=,iv:ImVMF6cabDElrkDMcanvRL1BPUaTbmKKyn/kNXXGg4o=,tag:U1rXjNsOlOiTwXo5maJZ6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSXNKWFAwUHR2YzJYSWo2
            bVY2djlybDl6UElNbHBoV0xRc2JPOXkzTmlnCmljdDJ0VjhmQjFISmlyK3pZT0k1
            R2JjTWF1U21PK096NXpzYk1QZmVGdTgKLS0tIHJXUGlvM2FEN0RiUWRLWTd2ejY4
            QjVUNkNBWEE1MW90RTZ2a0FmRGROaGMKt+IrQn0OWd6Mp63vISOAZLxLdjLiYM7L
            d5/KO+1vnREdMuvzg7tKq8o+3rUOp9tG57YVYAMkCLv2a0I/mixVDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T21:58:16Z"
    mac: ENC[AES256_GCM,data:5jzyKf6eJAnhSUZqWEDM3p5qCEGHVXUu/V9Ydx8pow+q2DiU0vVOovtLs5zOndF4FXnqUFoqipdvQ8loyiPYlpQSmaXHQnrn6wZ6TBb07+iSsYQ+ilaBhvL3/nX0+bMMxUW3ZlSUEcimIlbPUKN7uo1fOoC3jeFDLtKakSg/NJQ=,iv:TytVMFdJj0ip0mJZ+qUDtBFTpXEL1+Ln+6VeYE8D5NU=,tag:9Mlc+RMvNsZ06LKQUgrQCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
