kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: radarr-secret
    namespace: media
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:nTgfNDbRU1IpLXs+QP0Uc7dFgxh5Ye49PLQuU1T48rc=,iv:/2FKy/JkaE7JhGSowZJDVwv04jb1Kv9dmo11KtwSGa0=,tag:/WsTwVAo66KLHd3Grzcebg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia2NIQXpYYUUvQmd1eW44
            Z0tQeGZxUjFPa0ZzQlB5MjM0TVlONGVxZ2dJCklJNUxtQjhPakliV0hJYXJ2WVFa
            TkdaK0lwdlRiUm9HSU9ZUlE0MXNIWjgKLS0tIDhJQXBicUQzSTdpN2FCUHVZVllk
            THp2bDdOdGg4S2ZscUtScHZLdmgyRDgKt1u3LByLvqiFtfb24QMQhZo7OQLdV1yS
            YK0Vg4nS79WWqji1TjZL5I1j6LKvnEsNoGOlOhE4W5TkDxfac1rb4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-09T00:54:15Z"
    mac: ENC[AES256_GCM,data:9LjwUEo9pqGEhf+gcudmN6E0Ptz/l745VOv5FpPJqkjPCDx8swCv9POAQ1VNXrcxpBgVxiZC7pwl/6WjIr5+/4r5qOQ+OOXu57Ot8/AKh259d+E9WE9fNezjIrqL4ylMDne++w77kJNrlMG+liTvO5BUJUrxNEDSCKtfuIEnrek=,iv:fCsCLTcfO7jb9TxQwC47O3p8ROXg6wXNdkwZbdH/xUU=,tag:kSy+2lT9Jof5uCWVNqORqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
