---

# ssh_authorized_keys: []

ubuntu:
  packages:
    - hdparm
    - htop
    - ipvsadm
    - lm-sensors
    - nano
    - nfs-common
    - nvme-cli
    - socat
    - python3-kubernetes
    - python3-yaml
    - apt-transport-https
    - arptables
    - ca-certificates
    - curl
    - ebtables
    - fzf
    - gdisk
    - iputils-ping
    - lvm2
    - net-tools
    - ntpdate
    - open-iscsi
    - psmisc
    - smartmontools
    - software-properties-common
    - unzip