---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./edge-sw.yaml
  - ./madbuda.yaml
  - ./madhouse.yaml
  - ./nas.yaml
  - ./office-sw.yaml
  - ./subether.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
