---
apiVersion: v1
kind: ConfigMap
metadata:
  name: madhouse-domain-gatus-ep
  namespace: networking
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: domain_expiration_madhouse
        group: domains
        url: "https://madhouse.me
        interval: 1h
        conditions:
          - "[DOMAIN_EXPIRATION] > 720h"
        alerts:
          - type: pushover
