---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nas-gatus-ep
  namespace: networking
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: nas
        group: infra
        url: "icmp://${NAS}"
        interval: 1m
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
