---
apiVersion: v1
kind: ConfigMap
metadata:
  name: officesw-gatus-ep
  namespace: networking
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: office_switch
        group: infra
        url: icmp://192.168.10.6
        interval: 1m
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
