apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:51W/Y25Z4YN6/JwkiraS2w4vL4rnHukUjZar4hMFQkxuD8k2WvrwJqR2mYEYUJUFvX3ck0zV7qmvY70L,iv:/HMTdsOKLYlBagpMCpf9OGppAeVbE1XIT91aWZubJLA=,tag:VaUxxBZbSCY8LzvOsEh9CA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbWVLS2cwVWdiQ29qZ2I2
            VTBCTWdxRWUyOWdMVUpFRXNtR3FaZzBMTUhVCkZvSVhnWWNyRzhQbTNOZnJ5SXJ2
            QmZlQVZzK1AwR2xOMzRMT0NWL0hEZ0UKLS0tIFNtak5HcktKN3NwNGljNjBYL2pq
            TUQxMGFsRjQ2UTJCRklBQklrNEVIM0UK17Ab7U0KbGeqUGr2koqsff6Z8c8VG8Ai
            WYIX0lKXoy58wek8lITjV0tN1Dq27Nr5oB8UUdDeVX7YtIqTau3r8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-03T22:43:48Z"
    mac: ENC[AES256_GCM,data:CvRJVLcAm55mnkr7dWk4mq3ZY+l0ipXQSmeiPb0qw5Rwksk4eQ/RA2DiXPhKAqhOodAHfL1iJ2wN+qN8ttXfwSmnJduQxyqU4Ct2VYP40gFD21mWJnSNwptuitl1CCy7XXdHVdKPToI+3lZkRhwli9iixD4q3Jn1AD6AsYL76Cs=,iv:ANmvowE2OKuz8b5b+ntFD72EOHRjKTdd2IiXg9lI/As=,tag:EIiPtKiWOrQPbB/yO7TVRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
