apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:2H4V4Z+n0eOe1htxnDHmVkrGs3a05J8Zqr7MYml8lTULicOuZvpwz6lMM7//PCr1NFFtVMYSxG0cTkzR,iv:OysW8dAQRAjzQ8qeJs/2PbqgGochB3VMzpH5ILPD22c=,tag:+LNK774c698TGtl1XWiQtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueldYdlB3VGQzcUNRV1hC
            d1ozcGJKRVFZVG5saXhNeUhxKyswR2ZESzBJCll6OE5XbCtadHBJK0doNEcvU0Ft
            cXZlbVRmNDNGUjdjRDZ3OG9rVnVvWHMKLS0tIGVFc1hLQnRxSCs4Slp4RXRlUEZy
            TG5SL3VnOUljaXhWMGxBRXdCMEJmUk0KF1aIX8Igfr/fWqoZZycme0Odn8pyy9ZQ
            3vKwwQgfnpdXPUwArup+i111GYkWFEYxbsZKCRWxdrQw03uqG3R5NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-04T13:51:12Z"
    mac: ENC[AES256_GCM,data:iwYXd+4hpG8m6mDKJ5nHJc3zClU+LHkZ0wr6rWniSu0sn3BneMv+yLzodyqcu6vzHltgUjKTJpIDJOZni9dJI0yUcQMa1NZKxEVI4Nr+w/Y3PXhTQ+2+gKkWsiZoKSEkdfB29Nmd5tB4udhgBkmMIDLoAxvd0DjWeNl3M/La8g8=,iv:D9uXfMm6QxHcf83AzgxzmUUL1sBKk4SIzN31KpeMsm8=,tag:T9grdmXxSOKZ/NL6YSkajg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
