kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: plex-restic-secret
    namespace: media
stringData:
    B2_ACCOUNT_ID: ENC[AES256_GCM,data:fKMY+aqIrgSTGgfzRa7Y2GOx7nyrK/lhrA==,iv:yRIww1olewQz+ZN8SOLSbBlWIMxM9AvnXTXSLCbCnf0=,tag:vyBFuN62X0xlrT4faUJkwg==,type:str]
    B2_ACCOUNT_KEY: ENC[AES256_GCM,data:QkqSTXn6mnr2WFDTQtrzbJG0xldKcPPIF/1OHdUKPA==,iv:J3VzHvE49wtSrggn35aeqqIHSo8wYvtFyDa5aFzX9vg=,tag:ZDXyLv1ijoJpAzVienwcqw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:UL2KHc3ZgL7Qiw==,iv:8JTNqCQwuN/DQ1J1sooF/8QCqSlpAMTEfxb3ZxVrHHQ=,tag:xcRMCZwo8D6MJ8iMXoJqwA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:PMqAVm9vvOSL55o=,iv:4mzCOOCzM4lhSXCf6Cb1vcjQt4FGb11xMOksZ0ef1CU=,tag:E1mgrQgbbTB8OflnQ19J7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia2NIQXpYYUUvQmd1eW44
            Z0tQeGZxUjFPa0ZzQlB5MjM0TVlONGVxZ2dJCklJNUxtQjhPakliV0hJYXJ2WVFa
            TkdaK0lwdlRiUm9HSU9ZUlE0MXNIWjgKLS0tIDhJQXBicUQzSTdpN2FCUHVZVllk
            THp2bDdOdGg4S2ZscUtScHZLdmgyRDgKt1u3LByLvqiFtfb24QMQhZo7OQLdV1yS
            YK0Vg4nS79WWqji1TjZL5I1j6LKvnEsNoGOlOhE4W5TkDxfac1rb4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-11T00:23:33Z"
    mac: ENC[AES256_GCM,data:Ynk/9HayxqMf/z+Y3fjkToCsyojQcXCt+lhH3XiaPbdi1aKEeFq9aZLyTQT+iJGLq6oEX7q2lSw1MQv8BNjrseXnsmLxIYnOwakcYjbvEzGiN2GsFgJ8IorbH4mbaSVTGWsvA6DJHij1wKBlKURmO07mWeWaI2C4ad9NQRNZh7Y=,iv:1LN1B3zlBX4tShJs0gLvRkRz8rEoFo/TKgGmWRS9/qg=,tag:CAr/VlCL+Uz86ORrw2LYSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
