kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: zalando-postgres-cluster
    namespace: databases
stringData:
    password: ENC[AES256_GCM,data:yv3l7/r6JD3NtPc=,iv:P0ouMPDHHoRgvILroORVVfHRMxKViu1w84Q7J+AdYeI=,tag:8jRqQ3NLA9KMYDnILkd7QQ==,type:str]
    username: ENC[AES256_GCM,data:uCKdijUeNQ==,iv:Qtef+rOaroZK7Cq7ceRkK+8WzAo77ZYw1jypzxPdWRw=,tag:ZPCvdSnqt9QsPgqHv11riQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOK2dua0pEU3U2Yzhnb0tO
            Yndnc1NDblZuSTZHSmhRR3RqVEhPb1Z1ZlEwCjlBM1c5aVpKeW96OVFsdkYvcEtk
            blpTeWVSWEo0NzI4OTBqWkFmY054TlUKLS0tIG0vK2U0MHRpejViRDRVU0FVK2FI
            ZGZtc2M3cTh5bXBEZnBYRmh2dC9sRWcKthub+wJpkcrikoDu9/YkWtM9zaShLzjB
            4v3Z/vOm479kkX3p7qBoXoWfgJW2g4ArK59CMNEbxQcxWQgbBpJQbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T01:14:03Z"
    mac: ENC[AES256_GCM,data:zTg+jU/1OjdqmqwE9Sp0XMSwBUHUp4R4HdY8nzKUD0oNk987G8jZxb8Lq1GVb+FWCJUpafNFuLigfGtAFnYxah5Fjk5gUf8b3AgOTrrFDufrrtssPLeCGlQmQRnn2IQL3u8tMdqDQ89DFw/5cV2J2Afyybyj5CTxTXL+5XSWnBg=,iv:LH8DgmeXNscf/2wcXFAUIsRvhuVy2hERSGfnOTLyXsg=,tag:Afwd2ik5XUbiQt7yNWVv4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
