---
apiVersion: v1
kind: Service
metadata:
  name: postgres-ext
  namespace: databases
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "postgres-zalando.bjw-s.dev"
    io.cilium/lb-ipam-ips: "10.45.0.24"
spec:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/loadBalancerIPs: "${SVC_POSTGRESDB_ADDR}"
  externalTrafficPolicy: Local
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    application: spilo
    cluster-name: postgres
    spilo-role: master