---
apiVersion: v1
kind: Service
metadata:
  name: postgres-ext
  namespace: databases
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "postgres.${SECRET_DOMAIN}"
    metallb.universe.tf/loadBalancerIPs: "${SVC_POSTGRESDB_ADDR}"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    application: spilo
    cluster-name: postgres
    spilo-role: master