kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: plex-trakt-sync-restic-secret
    namespace: media
stringData:
    B2_ACCOUNT_ID: ENC[AES256_GCM,data:F2AXq/FuaqY7NcG8PWtI4lwlqou8+GV4JA==,iv:4hHQPiaPlssNVlT4aaLfqwpZTTq9mPFnIqvdbCxmZtM=,tag:+Z/h9Q8xwf7zC+BabikbEA==,type:str]
    B2_ACCOUNT_KEY: ENC[AES256_GCM,data:TytkMVPEmleBhWGcJDTvXKJiN2bydo54oWe1lfFnng==,iv:1+ApgoUIytvHwvTVMe97iHSQWhy1kTFS37u/4zZmTNE=,tag:mYMCr6LUCTkavpw4LQhxNw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:CQGZtoJ++FM4dMzSgTWvbw==,iv:rTDNMVGmkkg+R3q8VEvPGoKteL/OH5COMT2u/FJDXvA=,tag:8lFvyzZJ5s1v7Bd9EH21UA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:PMqAVm9vvOSL55o=,iv:4mzCOOCzM4lhSXCf6Cb1vcjQt4FGb11xMOksZ0ef1CU=,tag:E1mgrQgbbTB8OflnQ19J7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia2NIQXpYYUUvQmd1eW44
            Z0tQeGZxUjFPa0ZzQlB5MjM0TVlONGVxZ2dJCklJNUxtQjhPakliV0hJYXJ2WVFa
            TkdaK0lwdlRiUm9HSU9ZUlE0MXNIWjgKLS0tIDhJQXBicUQzSTdpN2FCUHVZVllk
            THp2bDdOdGg4S2ZscUtScHZLdmgyRDgKt1u3LByLvqiFtfb24QMQhZo7OQLdV1yS
            YK0Vg4nS79WWqji1TjZL5I1j6LKvnEsNoGOlOhE4W5TkDxfac1rb4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-11T00:24:05Z"
    mac: ENC[AES256_GCM,data:x905D3GVmzZ3/blXGXDZAEI256fyB/rt2VjJNfNdHGRPvGp3ZEONHWucu+ZqwKNrKGEyBh438kkbOxoqpPtNDs2gwf7tmMdWTrp7MtobMRNbvmJry5p5OsC5QOoMxyiGszmJjPIKPVfVv5oREamM93sR5Q8/ZfpO2Sy6g/Iq6eM=,iv:l26NKzbzpKorWPAsfoVf/ym/q9jwa2xnyQAsecgH/gQ=,tag:Jn0NMlCRU7c9jBRAzJtFOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
