---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-readarr
  namespace: flux-system
spec:
  path: ./kubernetes/apps/media/readarr/app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: rook-ceph-cluster
    - name: system-volsync
