# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:xDr1tMImA4zQD8e8Nh+0EdwNplQ2MKRRlyTzwSag1CK6ic3k2SOJGiCtXTlyzBH5u3kKu7MmHtWqu3hCh+4ykdPjedzMzxC5NpFwE6YBqcNKjgLX5yTSpkDnUOOsMtmhxlUebbulhzAjeAXy0ppCPJfZdMmh0Q0EX7zq6vir67xKtagAlLb7KhGAmIFxxFxuZSXTJ3z2S+oDFC3wbCdzMVA=,iv:r/7rKmBgfzY34ce8w2yBpXUcs1qj8KQGtXEv6XUoSF4=,tag:LaKubQZ4AQwKrj1v/5Op8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRHFaRGFOWW15ektHellE
            M1daZ2FSOVhFOFJQdExmQnNNSE5rSEFmYTBZCnp6Q3pNZm12TFpKV3pPS0xNVWs4
            UVR2ZDFnQlVWZThzYXcxRmhFcWFlb2cKLS0tIDFtMHNINjZObGU4R0piQlZYOW1o
            WmlrcjVjZDJSYm5uei9QaGN2VTkzbjAKz4JlMHzGdq2DeOfLqiDiga8kpqMoYjIi
            K8vQQLkAjsPOFC7aNPk+RsWgAJH7sjXhsxtE0Qkf1gjHQ5LnbqMX2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-04T17:04:27Z"
    mac: ENC[AES256_GCM,data:nRFe1r6dG376F2W0uKch8aNskPpUcNIbXknM6dz7evilIwwtY3d8NFY6qiRgxC2Md36EL3UEbna3dbf2Ck/piC8vHdLhkSP4wlQ88Bu0hy8J+CINNJhYGFW3pNOtzNrnK0iXKJqVbJHV3l8RhqpTJkaOUKsk9YDcmgEndliwnkw=,iv:r+FooZ2pwZgvCiJnTNVy2tt+8CoPMPyLS6GEovboMx4=,tag:/hz412tGF1RRKbYLaRDDkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
