# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:JUN5YLFwDjsM6DP8TITFDQcqYYfk/k1ooo1N8Io3cfj/O/os5b9wre/iTpSwJ5qO76AkQ9qahtSvd4y5xt/9ukTqSEqAoLsyT/OjlU0tfy1NdXJoRhwYrBptnRWIaTOGN+QpDGWvExSJ7UBAklcly3Zn6TDPM1vWTfqxG85JQ5h7f7uOg5z/MvcJ+g==,iv:AVZBZpknEHdnb+RBPqdmXS3E28lNtuaUCtjDTDZubHo=,tag:AYb6lyMhIboAMzB3Ry6TAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRHFaRGFOWW15ektHellE
            M1daZ2FSOVhFOFJQdExmQnNNSE5rSEFmYTBZCnp6Q3pNZm12TFpKV3pPS0xNVWs4
            UVR2ZDFnQlVWZThzYXcxRmhFcWFlb2cKLS0tIDFtMHNINjZObGU4R0piQlZYOW1o
            WmlrcjVjZDJSYm5uei9QaGN2VTkzbjAKz4JlMHzGdq2DeOfLqiDiga8kpqMoYjIi
            K8vQQLkAjsPOFC7aNPk+RsWgAJH7sjXhsxtE0Qkf1gjHQ5LnbqMX2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-04T16:54:56Z"
    mac: ENC[AES256_GCM,data:wuLmUHUd92MqjYSmWNX+4FDoDNeRbd4+4I/rFHUqI61C1+ohR9fq3Zh8sVqsJEV4bUYcndMIr8Q5GfJZx+EqHlco5s4gaCITn6ZK8vkS9QIIbWGjrJtOFjuE/gPOf0TlrDF4qiLtCTza1u65JSSRyZqeQqHo8ndmZWKEMiT7OgQ=,iv:q7NMKHnlnr6Nw1rgh2m426JbN3VfMO1ztO4EyH1BJPI=,tag:KaLZqkDMo6HFXhgQg4A58g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
