# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:90aZKTegeRknjgKKhDs+IPmj6U7M6+sMBi3zLfBotFrdJTYsBYG7kwj74llK4Yw9fu5dpqAXO2/Cq50pbwCuUmdW/Kt7S1xJyBrMGKPclaVPjIuLIUhrVHejsTCeMNPGxvPOQddndw5JtBuSbhBQiEzvfzEtRaFD5VqRRbgy2LUvPf90AOCYHzfKY5hlpc57MXy75PwP1JcvdCmO9rQM,iv:xRGaGGF59rzlsakAVBRDp5MWayv6IXC/Jn2o+qVIhF4=,tag:mZ8NMlJvxPMDujTKp0d/QA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRHFaRGFOWW15ektHellE
            M1daZ2FSOVhFOFJQdExmQnNNSE5rSEFmYTBZCnp6Q3pNZm12TFpKV3pPS0xNVWs4
            UVR2ZDFnQlVWZThzYXcxRmhFcWFlb2cKLS0tIDFtMHNINjZObGU4R0piQlZYOW1o
            WmlrcjVjZDJSYm5uei9QaGN2VTkzbjAKz4JlMHzGdq2DeOfLqiDiga8kpqMoYjIi
            K8vQQLkAjsPOFC7aNPk+RsWgAJH7sjXhsxtE0Qkf1gjHQ5LnbqMX2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-04T17:01:29Z"
    mac: ENC[AES256_GCM,data:ANnyndgB1988T9cj2Thfl/mT3S/qbu1ZMOVTvfN/JCpbZXtKWPi3A8sibiW+3QGv2bSyjYq1lD+7TGl3Z6zy6HylOsBOMwIMU8ZR2cBnuP5EFrLJlfHq71oNSMi8UTmW9U++LyKI+kzXZFSl4AWUZp+aqQR3hM+DQXIW6pVohSs=,iv:8s5wx99A34EE9H6PDDRMI9ZH6b+2jhHmbXabaljvnVQ=,tag:zJ7bTqPjc1gZ9X7LZRksEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
