apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:sDtEKnrpBxkFQP6f695xT2ksM2oGNqrv0ETG6BRo4LcNNjYS,iv:hSRCNmao6HJe54KYs70lwa357r9tBIjkA6L25wk8D2o=,tag:M65dFo5g/gPemz1czEanug==,type:str]
    credentials.json: ENC[AES256_GCM,data:vR3yiAu3wY80QL2IvFBInxuVdmXOQBMIFarT4X/XyUrhGIxnt16NCyBuppbRlEG3bhj6GYtUcFLXBts08km/8oGll/CsQczOUC97S5y1iDeRmqX8MicwmXl3zOLFt1ZfeUWv3QbvEuu37nasdEUh8cFJfa81VWCFiPMVfqLpk6MJDamVfp9rdAD3toj5aL++zKPLn6LbROF9NPc7sc0zzg2BobayheTWhtgewaRQIQ==,iv:G1AxtXRjJKQsDMS7rT1nr5YtIHH6o0+HDW+otn/dGrc=,tag:256coDAZfik5icNBOTqhyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMUVaRnlzVXdzbUd4MURr
            WHpxZDZhT3pLVk5jdGQrMDE2QzFaeVZGR0dVCjE1ZWE0ZVl5VW5pU0xYNTIyRUlH
            bDRvNTVHeEJOZXJJYVNkVzQzTFY4V1EKLS0tIG0vaGhCaXFmY0xNOFhVTXBESFJu
            T2pSbzdxYm1Ta1VrOEw3c3hVdW9RZU0KWRhBVSP05f9GEJI55ZN/6cSi+7gbC4BX
            lOHd2iR3eO/0uF4PH/XrBEbOv3vXayqtLiPnRqHf+9HVadkH90NrBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-04T13:51:11Z"
    mac: ENC[AES256_GCM,data:rQvzdtU3MAPWD6mymWda4FmrMsjDmkkI51wGCmDo4qUKsyvSL4kqMKVsFwl9PiQbzsJ4KaxXmu68j6p0SX2FyoK3O9j7bbzy11TV2uIWs46B/1C7XDtMiDqxWFqOGCv5yX66Qp36a5z/gCdTxYW8pv7VCgZkzCiV4Wzhe9N/YO8=,iv:lPf2jjCgx4YtR8h2cMj0AP4eGlCPDH5/7n/GRSTdfJo=,tag:JRkEO6O0UlYEAoI5bjx7xQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
