---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: printerdb-data-v1
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block