kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: calibre-web-restic-secret
    namespace: media
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:78be/JpvOPBgeocGFWh5/ivBAegjo8Bc75TDaoDSUpG9uXptL4q2DmfWuSSIvtM=,iv:rdPL2m7RmgvnjA+1qDo3a+yrZod6N5ojnpQzQ15VWkc=,tag:ko45qQ2BfET2tA3bYON05w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:PMqAVm9vvOSL55o=,iv:4mzCOOCzM4lhSXCf6Cb1vcjQt4FGb11xMOksZ0ef1CU=,tag:E1mgrQgbbTB8OflnQ19J7A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:8axRUpjx,iv:4w0TuSQ/cnAjr9etOQzQimeaktqdFG4wfXX62WNx6hs=,tag:jEUIAt0yFlqH+sIohe9ZlA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:arOBIF2jG76fNx5DfNo=,iv:K4ixvckm+4hQHZocCRCwY3Ufc+IKTY1IFBymfIvIL+w=,tag:tQnhekXqxhMu85VGzfC2zQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia2NIQXpYYUUvQmd1eW44
            Z0tQeGZxUjFPa0ZzQlB5MjM0TVlONGVxZ2dJCklJNUxtQjhPakliV0hJYXJ2WVFa
            TkdaK0lwdlRiUm9HSU9ZUlE0MXNIWjgKLS0tIDhJQXBicUQzSTdpN2FCUHVZVllk
            THp2bDdOdGg4S2ZscUtScHZLdmgyRDgKt1u3LByLvqiFtfb24QMQhZo7OQLdV1yS
            YK0Vg4nS79WWqji1TjZL5I1j6LKvnEsNoGOlOhE4W5TkDxfac1rb4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T14:48:28Z"
    mac: ENC[AES256_GCM,data:HJm7H12PUpNyDs3wXC9sF56cK38mMtnPNy2Jx0bI41R3YOhVr6yDcHkZMjfRN58yTc/Mx/qsOySME46zkH61q0TkBCKUXGOvJBtOIe7fy5no/HmQk/mlW/6WxCmPeBgBqrKr40q5TBD/NkEfFrhw32g05PWNfUIAZNIeYhdm5zQ=,iv:rUWTCLiYIpHuvFbRNTvfJrCaSMEuEravk3afqCyvRV8=,tag:OFwmb2rCGa1bvZYfZImb0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
