kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: calibre-web-restic-secret
    namespace: media
stringData:
    B2_ACCOUNT_ID: ENC[AES256_GCM,data:mCYXXGokXm4OPxmitQAuEtCO4BFnmwNCvA==,iv:Z72h23v308OE/A8Ee3u3EYcgZf/aZEx/Z6oH/PlbLus=,tag:QmrZPJstLns1u+m77gL+YA==,type:str]
    B2_ACCOUNT_KEY: ENC[AES256_GCM,data:VRAvIhOuTh4UiLxVdBfkBl8lhOEf8f7DegkyWyKWuw==,iv:MgVJ8+usUf3U5VeDbk6NhW4YicJUCvE3HlCEqowEdz8=,tag:rA6N3zMzjUEpXaK+ofidKg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:y78dh0643aX5L/5Kosftj5E=,iv:78PaK2W3XQcviRd0feRrB1n1ea81oTN0ecqV7fxuuSU=,tag:7FbexMvzyt/1dWnJuTS/oQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:PMqAVm9vvOSL55o=,iv:4mzCOOCzM4lhSXCf6Cb1vcjQt4FGb11xMOksZ0ef1CU=,tag:E1mgrQgbbTB8OflnQ19J7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia2NIQXpYYUUvQmd1eW44
            Z0tQeGZxUjFPa0ZzQlB5MjM0TVlONGVxZ2dJCklJNUxtQjhPakliV0hJYXJ2WVFa
            TkdaK0lwdlRiUm9HSU9ZUlE0MXNIWjgKLS0tIDhJQXBicUQzSTdpN2FCUHVZVllk
            THp2bDdOdGg4S2ZscUtScHZLdmgyRDgKt1u3LByLvqiFtfb24QMQhZo7OQLdV1yS
            YK0Vg4nS79WWqji1TjZL5I1j6LKvnEsNoGOlOhE4W5TkDxfac1rb4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-11T00:23:00Z"
    mac: ENC[AES256_GCM,data:A+NjuedwQ2l6KEfnNGt7wtM+tLMSZ4eiEkcvCsjkKeyvsutqwLrqtgyghy1gCIVSS625Tv5hTy7eIBQAEPykTwRRb0JsCNtNnwO3y6V4ZEcRhXjVnY+70C6Fgm//wOC5r7xS+gv2QpSM+spjDzLYW6xgubv/qOCLyBxQ+kb0O+c=,iv:VbOGxpDUwkIPUJwhvs4FGXXq4nE43+cw9XjT06TC3Tw=,tag:5FMwzyfV7i3YQP4OtjnAXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
