kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: overseerr-exporter-secret
    namespace: monitoring
stringData:
    OVERSEERR_APIKEY: ENC[AES256_GCM,data:5NYk63wh6z049wobDvKYgU3yLkXmwGhc06VhGbMRpi31Y1p9hl51Lyaw4nFEtT0tDWfSna7Og0M1QpPXP14oaI1wr9A=,iv:ShjPZ52/6ado/02xycgcUUKKBBKKjh+dL7rEyBa4lds=,tag:qwL51NkDBvsADjn1fG7k5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a4dx6rtr4xakzwlr7tg7djdffqqmlnzfsxjzksmpus35gzz454gqnww8p0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWnNGVTFJcmVsTS82S0wy
            czVWaFFOU082L0pVYzJYT3dZUzFTNXM5TDAwClo0V3dhS2pxWWdWcFFHNXdoemsz
            bG03SlE2R2l6UTkvTGJMZ0luTFVCV0EKLS0tIG9kSjArTTRLQmhvK2tNSVU5S1hr
            ZTdOb2dyV3ArckdpQzlQZENSa25kSjAKNSLo6hkVVKhbq0KxCvFXjoV20CuQWoIe
            KNQ0txWCDeqS4wz0an1oUdFV3fweiZIQTFzp1lCFfn9SzyBa7dxpeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-07T00:14:45Z"
    mac: ENC[AES256_GCM,data:DyE0op3oK6Fp4a7SaU+qRa64DsMDsZwntEJ45NRvc6QxiAWcWhYyTp70xAxeTZ158NTDbbIG2JCpS8yFVgXqhcr0KdcOB7CbQbeQlChuqyaP82uAXv9sHvGBby1kfdZq7L6iGs54AzInsPzKN0M2k70ISVSz3JOAaucUuNG7OJM=,iv:kQ+7kdhSVF1uPYNxG3ZGlps37J8+5ZwZbt5BuxJQ0aA=,tag:TS6CkLrF8kH0Apk0V+trhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
