---
name: "Flux Diff"

on:
  pull_request:
    branches: ["main"]
    paths: ["**.yaml"]

jobs:
  flux-diff:
    name: Flux Diff
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      matrix:
        path: ["kubernetes"]
        resource: ["helmrelease", "kustomization"]
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: generate-token
        with:
          app_id: "${{ secrets.MAD_APP_ID }}"
          private_key: "${{ secrets.MAD_PRIVATE_KEY }}"

      - name: Diff Resources
        uses: allenporter/flux-local/action/diff@main
        id: diff
        with:
          path: "${{ matrix.path }}"
          resource: "${{ matrix.resource }}"

      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Add comment
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
        with:
          repo-token: "${{ steps.generate-token.outputs.token }}"
          message-id: "${{ github.event.pull_request.number }}/${{ matrix.path }}/${{ matrix.resource }}"
          message-failure: Diff was not successful
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
